# Author: Alexander Michels <michels9@illinois.edu>
# cybergisx/pysal-access:0.0.1
# https://hub.docker.com/repository/docker/cybergisx/pysal-access
# Changes:
# * Pegged pysal/access package to specific commit
FROM jupyter/minimal-notebook:2022-01-12

RUN python -m pip install git+https://github.com/pysal/access@c2fc9a1a6c92a223ebe3157c1b4bc248eacc691f
