# This is a basic workflow to help you get started with Actions
# flow from here: https://www.learncloudnative.com/blog/2020-02-20-github-action-build-push-docker-images
name: Docker Images Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push but only for the master branch and only if certain paths were changed
  push:
    branches: [ main ]
    paths: [ '**/Dockerfile' ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Runs a single command using the runners shell
      - name: Build image
        run: |
          for versionFilePath in $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} ${{ github.event.before }} | grep "Dockerfile");
          do
            folder=${versionFilePath%"/Dockerfile"}
            echo $folder
            docker build $folder --file $folder/Dockerfile
          done;
      
